# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "thelinux.pro"
email: "thiswillnotwork@thelinux.pro"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thelinux.pro" # the base hostname & protocol for your site

twitter_username: kameronkenny
github_username:  kkenny
linkedin_username: kameronkenny

google_analytics: "UA-118953072-1"

favorite_books:
  - name: "Extreme Ownership"
    subtitle: "How U.S. Navy SEALs Lead and Win"
    url:  'https://books.google.com/books?id=tpspDwAAQBAJ'
    author: "Jocko Willink, Leif Babin"
  - name: "Multipliers"
    url:  'https://books.google.com/books?id=kF26e_S6l_cC'
    author: "Liz Wiseman, Greg McKeown"
  - name: "The Phoenix Project"
    url:  'https://books.google.com/books?id=_An-CAAAQBAJ'
    author: "Gene Kim, Kevin Behr, George Spafford"

currently_reading:
  - name: "The Captain Class"
    subtitle: "A New Theory on Leadership"
    url:  'https://books.google.com/books?id=pKD4DAAAQBAJ'
    author: "Sam Walker"

work_disclaimer: "This site contains my thoughts and opinions, and doesn't reflect those of the company I work for."
copyright: "Copyright 2019, Kameron Kenny"

# Build settings
markdown: kramdown


theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
